### PR TITLE
Added WFIRST_CGI_20180103 mask

### PR DESCRIPTION
**Pull request by leonidprinceton**
converted gen_pupil_WFIRST_20180103.
However, this doent's produce exactly the same result as the current MATLAB implementation.
The new _LC_single_trial_mp_data.py file (used for comparison) was generated by running MATLAB's gen_pupil_WFIRST_20180103 with:
floor(interp2(Xs0,Xs0.',pupil1,Xs1,Xs1.','nearest',0))
instead of
interp2(Xs0,Xs0.',pupil1,Xs1,Xs1.','linear',0)

### CODE REVIEW

**Comment by mperrin** [comment]
Can I suggest not adding the comparison files to the repo as Python source with gargantuan lists of floating point numbers written in string format? That’s a very inefficient data storage form. Much better to save it as a binary file instead, either .mat or .fits.

**Comment by leonidprinceton** [comment]
Eventually, when we have the definitions of all classes, we can give them a constructor from ".mat" files.
Meanwhile, we can use the "init_from_mat" functions, but it takes 6 seconds to execute every time.
On the other hand, the .py files are compiled into .pyc just once and then it's very quick.

I suggest leaving this for when we have the class hierarchies.

**Comment by mperrin** [comment]
I'm not convinced that speed of execution to save a few seconds running the comparison tests is something worth to optimize for!  Alternatively, one thing to be aware of with git is that objects added to the repository are stored there forever, even if the files are later deleted. So this approach will just end up proliferating lots of huge awkward text files into the repository forever. Yes disk is cheap, but still I'm not sure this is worth doing. 

Secondly, the current implementation is storing all these things as plain Python lists, rather than Numpy ndarrays. This is orders of magnitude less efficient for doing calculations on, and likewise extremely inefficient for memory usage. This stuff all ought to be in numpy arrays, not lists.

**Comment by leonidprinceton** [comment]
I totally agree that this is a bad solution in the long run. I'll remove that file and replace it with a .mat as soon as we define the classes with an option for loading .mat files.
Currently, the test functions in test_masks have no performance issues with Python lists, but it takes me hours to debug them, unless the .pyc file is present.

**Comment by ajeldorado** [comment]
Can

**Comment by ajeldorado** [comment]
Oops, I didn't mean to close the pull request, sorry. Please send again to add it.
Leonid, I added you as a collaborator, so I think you can pull now yourself. Please verify.

**Pull request closed without merging**
